version: '3.8'

services:
  api:
    build: .
    ports:
      - "5001:5001"
    environment:
      - AWS_REGION=${AWS_REGION:-eu-central-1}
      - AWS_SECRET_NAME=${AWS_SECRET_NAME:-coursesdb-connection-string}
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
